### ISSUE TITLE
sonarr_youtubedl: Support for cookies.txt

### ISSUE THREAD

**Issue by RandomNinjaAtk** [whatdaybob/Custom_Docker_Images#8] opened 2020-08-16 21:17 UTC
Attempting to use this, but cannot use it at the moment because of the need for cookies.txt

**Comment by RandomNinjaAtk** [comment] 2020-08-16 21:19
Could be as simple as detecting the cookies.txt file is located in the configuration directory and use it, if available...

**Comment by whatdaybob** [comment] 2020-08-17 16:22
Hi @RandomNinjaAtk, never used a cookies.txt file personally before but happy to look into. I am guessing that the cookie file is different for each site so as you suggested it would be best to have it in the config directory but also an entry in the yml specifying which to use on a per show basis. 

Can I ask what site you are using a cookies file for and what your normal use code is for me to reference and test against?

**Comment by RandomNinjaAtk** [comment] 2020-08-17 16:39
So primarily I've only ever used it for youtube, see this issue on my own repo:
https://github.com/RandomNinjaAtk/docker-amtd/issues/6

The user is receiving a error 429, too many requests. I see the exact same issue with youtube in my own setup, and I've only ever resolved it using the cookies option. I ran into the same error when attempting to get your docker image working, which is why I'm requesting this and I was only using your sample channel to test at first.

Here is how I've implemented it in one of my scripts:

This and the following few lines I detect the file and assign the option directly to a variable:
https://github.com/RandomNinjaAtk/docker-amtd/blob/master/root/scripts/download.bash#L39

Then on this line, where youtube-dl is executed, I just include the variable:
https://github.com/RandomNinjaAtk/docker-amtd/blob/master/root/scripts/download.bash#L129

So its fairly straight forward. Let me know if you need any more info.

youtube-dl options info: https://github.com/ytdl-org/youtube-dl#filesystem-options

**Comment by whatdaybob** [comment] 2020-08-17 16:47
Thanks for the information and code examples. Can't say I have ever received that error with YouTube and the script runs every minute. I suppose if I were to do slam the api I may receive it but very unlikely reproducible with a consistency to testing. Will get the above in and see what happens when I delete all web series and spam the api.

**Comment by whatdaybob** [comment] 2020-08-17 22:28
@RandomNinjaAtk I have now updated the dev branch with the required changes and also created a dev tag on docker hub. Can you please give [whatdaybob/sonarr_youtubedl:dev](https://hub.docker.com/r/whatdaybob/sonarr_youtubedl/tags) a try, 

Example config is available [here](https://github.com/whatdaybob/Custom_Docker_Images/blob/4fa00094eb268f664814ea1f8a7717a0810a4c48/sonarr_youtubedl/app/config.yml.template#L14).

**Comment by RandomNinjaAtk** [comment] 2020-08-18 10:25
I'll give this a try today and report back

**Comment by RandomNinjaAtk** [comment] 2020-08-18 10:39
@whatdaybob still getting the same error, cannot tell if it  is using the file 

![image](https://user-images.githubusercontent.com/8386416/90503476-774c1f00-e11d-11ea-9d6b-c974fbeeb7d3.png)

**Comment by whatdaybob** [comment] 2020-08-18 10:43
Thanks for testing @RandomNinjaAtk i will have a look into again, I can't find a solid way to reproduce the error unfortunately, will triple check I'm loading the cookie file on search as that's seems to be where your getting that error. Sorry about that.

**Comment by RandomNinjaAtk** [comment] 2020-08-18 10:45
Maybe if you added a debug option, to output the command it's sending to youtube-dl, I could more easily help troubleshoot it.

**Comment by whatdaybob** [comment] 2020-08-18 10:58
Sure thing, I can print the string when I add the extra cookies string to it. 

Looking into the issue from YouTube-dls side there is a lot of closed issues all pointing to [here](https://github.com/ytdl-org/youtube-dl/issues/22382) as unresolved. Not everyone's issues are resolved by cookies.txt, I may see if I can PR and fix on YouTube-dl with the mentioned code but not sure how often releases are done on that project. 

Anyways will get that implemented in dev ASAP for you.

**Comment by RandomNinjaAtk** [comment] 2020-08-18 11:55
@whatdaybob Yeah, its a tricky issue, I only know that cookies resolved it for me, cause I have a trailer downloading script (the one linked earlier) and music video downloading script that both experienced the same issue and was resolved using cookies in my personal case.

I appreciate your time in this, feel free to checkout my repos...

**Comment by whatdaybob** [comment] 2020-08-18 14:40
@RandomNinjaAtk, I have a new build up on docker, you will need to check the dev branch config.yml.template to get the debug on. I have changed how the path handling works to ensure that I check the file exists and use the absolute path. hope this sorts it, still not able to reproduce at all, spammed it with thousands of requests and not an issue raises. I have heard rumours that ipv6 is the cause and disabling this sorts this issues, may be worth testing as a resolution to your woes as well.

**Comment by RandomNinjaAtk** [comment] 2020-08-18 15:07
Looks like they may have fixed it (not seeing the error), although I'm not sure its still working. Maybe a volume mapping I have set is incorrect or some other issue. I'm only attempting to use your first 2 examples from the config template

One thing would be nice, the script outputted to a log file, instead of console only for easier tracking...

**Comment by whatdaybob** [comment] 2020-08-18 15:55
Ok, sounds good that it's all cleared up, if your happy to close this issue for now let me know, can always reopen if it pops back up. 

I have opened a new enhancement for your suggestion on logging. [#17](https://github.com/whatdaybob/Custom_Docker_Images/issues/17) will cover this. Will start it after I finish up the in progress work.

**Closed as completed** 2020-08-18 17:37 UTC
Labels: enhancement

**Comment by whatdaybob** [comment] 2020-08-19 00:36
@RandomNinjaAtk FYI logging has now been better implemented. there is now a log file and debug will make both the console and the file write debug lines.
